/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */

plugins {
    `java-library`
    application
    id("com.github.johnrengelman.shadow") version "5.0.0"
    kotlin("jvm") version "1.3.21"
}

repositories {
    mavenCentral()
    maven("https://oss.sonatype.org/content/repositories/snapshots/")
}


application {
    mainClassName = "team.hdt.engine.HelloWorld"
}

dependencies {
    implementation("org.lwjgl", "lwjgl", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-assimp", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-bgfx", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-bullet", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-cuda", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-egl", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-glfw", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-jawt", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-jemalloc", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-libdivide", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-llvm", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-lmdb", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-lz4", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-meow", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-nanovg", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-nfd", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-nuklear", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-odbc", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-openal", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-opencl", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-opengl", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-opengles", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-openvr", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-opus", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-ovr", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-par", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-remotery", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-rpmalloc", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-sse", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-stb", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-tinyexr", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-tinyfd", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-tootle", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-vma", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-vulkan", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-xxhash", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-yoga", "3.2.2-SNAPSHOT")
    implementation("org.lwjgl", "lwjgl-zstd", "3.2.2-SNAPSHOT")
    runtimeOnly("org.lwjgl", "lwjgl", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-assimp", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-bgfx", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-bullet", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-glfw", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-jemalloc", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-libdivide", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-llvm", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-lmdb", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-lz4", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-meow", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-nanovg", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-nfd", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-nuklear", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-openal", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-opengl", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-opengles", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-openvr", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-opus", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-ovr", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-par", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-remotery", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-rpmalloc", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-sse", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-stb", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-tinyexr", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-tinyfd", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-tootle", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-vma", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-xxhash", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-yoga", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    runtimeOnly("org.lwjgl", "lwjgl-zstd", "3.2.2-SNAPSHOT", classifier = "natives-windows")
    implementation("org.joml", "joml", "1.9.13")
    implementation("com.code-disaster.steamworks4j", "steamworks4j", "1.8.0")
    implementation(kotlin("stdlib"))
}